Tables
Layer-Fi/layer-react pull request #202
Opened 2024-06-26 12:53 UTC by ArkuVonSymfon

2024-07-08 08:08 UTC, tomaszantas requested changes

2024-07-08 08:08 UTC, tomaszantas commented on src/components/TableBody/TableBody.tsx
> +export const TableBody = ({ children }: TableHeadProps) => {
```suggestion
export const TableBody = ({ children }: TableBodyProps) => {
```

2024-07-08 08:08 UTC, tomaszantas commented on src/components/TableBody/TableBody.tsx
> +  const tbodyClassNames = classNames('Layer__table-body')
single class, so I believe that `classNames` is no needed here

2024-07-08 08:08 UTC, tomaszantas commented on src/components/TableHead/TableHead.tsx
> +}
```suggestion
export const TableHead = ({ children }: TableHeadProps) => (
  <thead className='Layer__table-header'>{children}</thead>
)
```

2024-07-08 08:08 UTC, tomaszantas commented on src/icons/ChevronDownFill.tsx
> +    viewBox={`0 0 18 18`}
do we need this change here?

2024-07-08 08:08 UTC, tomaszantas commented on src/types/table.ts
> +  children: React.ReactNode | React.ReactNode[]
Let's try to deconstruct these elements, for example:

```
import { ReactNode } from 'react'

(...)
children: ReactNode
(...)
```

This probably should also work with `Fragment`

2024-07-08 08:28 UTC, tomaszantas commented
### Balance sheet

1. don't we want to have first level expanded by default? Like in Profit and Loss?

![image](https://github.com/Layer-Fi/layer-react/assets/11715931/93bf7e46-4fa0-4233-bbf8-0d1cc84e46c3)

2. `Collapse all rows` - I think it doesn't work
3. Would be good to have `cursor` on expandable rows, and maybe some hover effect ie. background color?
4. I feel that expanding animation still could be faster
5. Not sure if we need to animate table/list when we change date in the date picker - only on initial load, and then something subtle

2024-07-08 09:14 UTC, oliwia1003 approved these changes
LGTM

2024-07-09 12:12 UTC, tomaszantas approved these changes
LGTM!

2024-07-09 13:04 UTC, merged