feat: profit and loss chart - sync and empty states
Layer-Fi/layer-react pull request #312
Opened 2024-08-20 15:23 UTC by tomaszantas

## Description

Support syncing and no-data states on profit and loss chart.

## How this has been tested?

1. NO syncing and NO data

_Bars are just gray placeholders with no action on click_

![image](https://github.com/user-attachments/assets/b8f3837c-2edd-4065-91f3-691f6689e440)

2. NO syncing and data

![image](https://github.com/user-attachments/assets/0c1c255b-5c65-41cb-8bf1-f0e40be1d9c4)

3. Syncing and NO data

_Bars have same animation as in loading state_

![image](https://github.com/user-attachments/assets/90556878-6fd2-4989-b91b-da609e60dfb7)

4. Syncing and data

![image](https://github.com/user-attachments/assets/7bdd7fbd-9b70-4ac0-989c-099870cab2da)

2024-08-20 15:26 UTC, tomaszantas commented on src/components/ProfitAndLossChart/ProfitAndLossChart.tsx
> +  }, [data])
Not sure how to capture that there is no data... Above, I'm looking for any non-zero value

2024-08-21 02:27 UTC, doneel requested changes
@tomaszantas I'm seeing the absolute positioning behave rudely on different layouts. Here's an example of a client page layout where the pnl chart is on a different page layout than our default page. It shows up over a different component (and gets cut off, but I circled it)
![image](https://github.com/user-attachments/assets/67135eb0-76ab-4d98-8a54-16f113ffbe7b)

2024-08-21 10:02 UTC, tomaszantas commented
@doneel I fixed this in above [commit](https://github.com/Layer-Fi/layer-react/pull/312/commits/97709e02dac0ba63c0497ce60c8dc6f5039d03f0) by adding `position: relative` to the parent component.

2024-08-26 20:06 UTC, doneel approved these changes

2024-08-26 20:06 UTC, merged